.TH VRMS-RPM 1
.SH NAME
vrms-rpm - Report der installierten kommerziellen Software
.SH SYNOPSIS
\fBvrms-rpm\fR \fI[OPTION]\fR ...
.SH BESCHREIBUNG
Dieses Programm ist ein Clone des Originals
\fBvrms\fR ("\fBvirtual Richard M. Stallman\fR")
Programm fuer Debian GNU/Linux, geschrieben mit der Absicht diese  
brilliante Idee ueber die RPM-basierten GNU/Linux Distrubitionen zu bringen.
.PP
Dieses Programm analysiert die  installierten RPM Pakete und gibt eine 
Liste der gefundenen proprietaeren Pakete nach stdout aus. Die Entscheidung 
ueber die Klassifizierung eines proprietaeren oder freien Paketes erfolgt
nach den Fedora Projekt Lizensierungs-Richtlinien.
.PP
Fedora / CentOS User die zusaetzliche Repositories nutzen, wie z.B.
\fBRPM Fusion\fR, werden bemerken, dass nicht alle Pakete die aus 
nicht offiziellen Quellen kommen als proprietaer angezeigt werden.
Die Anzeige basiert, wie bereits vorher erwaehnt, auf der Paket Lizenz.
Es gibt vielfaeltige Gruende, neben der Lizenz, warum ein Paket nicht in
den offiziellen Quellen akzeptiert wird. 
.PP
Richard Stallman war ueber Jahre hinweg die promineteste und einflussreichste
Person in der freien Softwarebewegung, unermuedlich erinnert er uns an Fragen 
der Software Ethik. Wie Richard, glauben wir das Anwender eine einfache
Moeglichkeit haben sollten um festzustellen ob sie freie oder kommerzielle
Software auf ihrem System betreiben. Dieses Programm ist ein Versuch diese
Moeglichkeit zu schaffen. 
.SH OPTIONS
.TP
\fB\-\-ascii\fR
Display rms ASCII-art wenn keine proprietaere Pakete gefunden wurden
oder wenn proprietaere Pakete 10%% oder mehr der gesamten Pakete ausmachen.
.TP
\fB\-\-explain\fR
Bei den gelisteten Paketen sind die gezeigten Lizenzen da, um proprietaere
und freie Pakete zu klasifizieren.
.TP
\fB\-\-help\fR
Zeigt eine kurze Hilfe an und beendet das Programm.
.TP
\fB\-\-list\fR <\fInone\fR, \fIfree\fR, \fInonfree\fR, \fIall\fR>
Abgesehen von der Anzeige einer zusammenfassenden Anzahl von freien
und proprietaeren Paketen, werden sie alphabetisch angezeigt. 
Der default Wert ist proprietaer(non-free).
.TP
\fB\-\-version\fR
Zeige Version und beende das Programm.
.SH SEE ALSO
.TP
\fBhttps://fedoraproject.org/wiki/Licensing:Main#Good_Licenses\fR
Die Fedora Project Wiki Seite ueber akzeptierte Software Lizenzen.
.TP
\fBhttps://vrms.alioth.debian.org/\fR
Ort des originalen \fBvrms\fR Programms.
.SH LICENCE
Dieses Programm steht unter den Bedingungen der GNU General Public
Lizenz, Version 3, veröffentlicht von der Free Software Foundation.
.SH AUTHOR
Geschrieben Anfang 2017 von \fBsuve\fR.
