.TH VRMS-RPM 1
.SH NAME
vrms-rpm - Report der installierten kommerziellen Software
.SH SYNOPSIS
\fBvrms-rpm\fR \fI[OPTION]\fR ...
.SH DESCRIPTION
Dieses Programm ist ein Clone des Originals
\fBvrms\fR ("\fBvirtual Richard M. Stallman\fR")
Programm fuer Debian GNU/Linux, geschrieben mit der Absicht diese  
brilliante Idee ueber die RPM-basierten GNU/Linux Distrubitionen zu bringen.
.PP
Dieses Programm analysiert die Liste der installierten RPM Pakete und berichtet
eine Liste der gefundenen kommerziellen Pakete nach stdout. Die Entscheidung 
ueber die Klassifizierung eines kommerziellen oder freien Paketes erfolgt
nach den Fedora Projekt Lizensierungs-Richtlinien.
.PP
Fedora / CentOS User die zusaetzliche Repositories nutzen, wie z.B.
\fBRPM Fusion\fR, werden bemerken, dass nicht alle Pakete die aus 
nicht offiziellen Quellen kommen als kommerziell angezeigt werden.
Die Anzeige basiert, wie bereits vorher erwaehnt, auf der Paket Lizenz.
Es gibt vielfaeltige Gruende, neben der Lizenz, warum ein Paket nicht in
den offiziellen Quellen akzeptiert wird. 
.PP
Richard Stallman war ueber Jahre hinweg die promineteste und einflussreichste
Person in der freien Softwarebewegung, unermuedlich erinnert er uns an Fragen 
der Software Ethik. Wie Richard, glauben wir das Anwender eine einfache
Moeglichkeit haben sollten um festzustellen ob sie freie oder kommerzielle
Software auf ihrem System betreiben. Dieses Programm ist ein Versuch diese
Moeglichkeit zu schaffen. 
.SH OPTIONS
.TP
\fB\-\-ascii\fR
Display rms ASCII-art wenn keine kommerziellen Pakete gefunden wurden
oder wenn kommerzielle Pakete 10%% oder mehr der gesamten Pakete ausmachen.
.TP
\fB\-\-explain\fR
Bei den gelisteten Paketen sind die gezeigten Lizenzen da, um kommerzielle
und freie Pakete zu klasifizieren.
.TP
\fB\-\-help\fR
Zeigt eine kurze Hilfe an und beendet das Programm.
.TP
\fB\-\-list\fR <\fInone\fR, \fIfree\fR, \fInonfree\fR, \fIall\fR>
Abgesehen von der Anzeige einer zusammenfassenden Anzahl von freien & kommerziellen
Paketen, werden sie alphabetisch angezeigt. Der default Wert ist kommerziell(non-free).
.TP
\fB\-\-version\fR
Zeige Version und beende das Programm.
.SH SEE ALSO
.TP
\fBhttps://fedoraproject.org/wiki/Licensing:Main#Good_Licenses\fR
Die Fedora Project Wiki Seite ueber akzeptierte Software Lizenzen.
.TP
\fBhttps://vrms.alioth.debian.org/\fR
Home of the original \fBvrms\fR program.
.SH LICENCE
This program itself is available under the terms of the GNU General Public
License, version 3, as published by the Free Software Foundation.
.SH AUTHOR
Written in early 2017 by \fBsuve\fR.
