.TH VRMS-RPM 1
.SH NAME
vrms-rpm - maakt een rapport van geïnstalleerde niet-vrije software
.SH SAMENVATTING
\fBvrms-rpm\fR \fI[OPTIE]\fR ...
.SH BESCHRIJVING
Dit programma is een kloon van het oorspronkelijke
\fBvrms\fR ("\fBvirtuele Richard M. Stallman\fR")
programma voor Debian GNU/Linux, gemaakt om zijn briljante idee 
over te brengen naar RPM-gebaseerde GNU/Linux distributies.
.PP
Dit programma analyseert de lijst van momenteel geïnstalleerde RPM paketten en
rapporteert gevonden niet-vrije paketten naar stdout. De beslissing of een pakket
vrij of niet-vrij is, wordt gebaseerd op de licentierichtlijnen van het Fedora Project.
.PP
Fedora / CentOS gebruikers die extra softwarebronnen als  \fBRPM Fusion\fR gebruiken, 
kunnen merken dat niet alle paketten die uit niet-officële bron komen gemarkeerd
worden als niet-vrij. Dit is omdat het onderscheid gemaakt wordt, zoals eerder
vermeld, op basis van de licentie. Buiten licentie zijn er nog vele redenen
waarom een pakket niet in de officiële bronnen geaccepteerd kan worden
voor Fedora / CentOS - zoals softwarepatenten of exportbeperkingen.
.PP
Richard Stallman is al sinds jaren, de meest prominente en mondige figuur
in de Vrije Software-beweging, die ons rusteloos herinnert aan de problemen
van software-ethiek. Zoals Richard, geloven wij ook dat gebruikers een
eenvoudige manier moeten hebben om te weten of ze niet-vrije software
op hun systeem hebben.
Dit programma is een poging om die noden te vervullen.
.SH OPTIES
.TP
\fB\-\-ascii\fR
Toont rms ASCII-kunst wanneer er geen niet-vrij pakketten zijn gevonden,
of wanneer niet-vrije paketten 10% of meer van het totaal vormen.
.TP
\fB\-\-explain\fR
Bij het oplijsten van paketten, toon de licenties om de vrij- niet-vrij
classificatie te motiveren.
.TP
\fB\-\-help\fR
Toont een korte helptekst voor dit programma en stopt.
.TP
\fB\-\-list\fR <\fInone\fR, \fIfree\fR, \fInonfree\fR, \fIall\fR>
Toon niet alleen het aantal vrije en niet-vrij pakketten,
noem ze ook bij naam.
De standaardwaarde voor deze optie is "\fInonfree\fR".
.TP
\fB\-\-version\fR
Toont versie-informatie en stopt.
.SH ZIE OOK
.TP
\fBhttps://fedoraproject.org/wiki/Licensing:Main#Good_Licenses\fR
De (Engelstalige) wiki van het Fedora Project over geaccepteerde
software-licenties.
.TP
\fBhttps://vrms.alioth.debian.org/\fR
Startpagina van het originele \fBvrms\fR programma.
.SH LICENTIE
Dit programma zelf is beschikbaar onder de voorwaarden van de
GNU General Public License, versie 3, zoals gepubliceerd door
de Free Software Foundation.
.SH AUTEUR
Geschreven in het begin van 2017 door \fBsuve\fR.
