.TH VRMS-RPM 1
.SH İSİM
vrms-rpm - Ücretsiz olmayan yüklü yazılımların rapor edilmesi
.SH ÖZET
\fBvrms-rpm\fR \fI[seçenekler]\fR ...
.SH TANITIM
Bu program orijinalinin bir klonudur.
\fBvrms\fR ("\fBvirtual Richard M. Stallman\fR")
Bu program kendi müthiş fikrini bütün RPM bazlı ve
 GNU/Linux sürümlerinde çalışmak üzere yaratılmıştır.
.PP
Bu program kurulu RPM paketlerini analiz eder ve ücretli paketleri stdout
 a rapor eder. Bir paketin ücretli veya ücretsiz olduğunun sınıflandırmasını
 Fedora Project lisansında bulunan rehberlerden faydalanarak yapar.
.PP
Fedora / CentOS kullanıcıları ekstra depolar kullanır, şunun gibi
\fBRPM Fusion\fR,belki tüm paketlerin resmi olamayan ve ücretli bir
depodan geldiği konusunda uyarabilir. Bu ayrımdan dolayı olur, önceden de
belirtildiği gibi, ve paket lisansına göre yapılır. Çeşitli nedenleri vardır,
lisanslama dışında, neden bir paket resmi Fedora / CentOS deposuna kabul
edilmez – nedenleri de örneğin yazılım patentleri ve dışarı çıkarma
kısıtlamalarıdır.
.PP
Richard Stallman Free Software hareketinde yıllardır
en belirgin vokal figür olmuştur amansızca yazılım etiğ, sorunlarını
hatırlatırken. Richard gibi, biz de kullanıcıların bilgisayarlarındaki
ücretsiz olmayan uygulamaların çalıştığı konusunda kolay bir yola sahip
olmalarına inanıyoruz. Bu program bu ihtiyacı yerine getirmek için
bir denemedir.
.SH SEÇENEKLER
.TP
\fB\-\-ascii\fR
Ücretli menü bulunmazsa ya da ücretli paketler 10% ve fazlaysa
, rms ASCII-art tablosunu göster.
.TP
\fB\-\-explain\fR
Paketleri listelerken, lisansları ücretsiz veya ücretli sınıflandırma için
ve kanıtlamak için göster.
.TP
\fB\-\-help\fR
Program için küçük bir yardım  menüsü göster ve kapat.
.TP
\fB\-\-list\fR <\fInone\fR, \fIfree\fR, \fInonfree\fR, \fIall\fR>
Ücretli veya ücretsiz paketlerin toplam sayısı dışında, paketleri ada göre
listeler.
Ayarlar için varsayılan değer: "\fInonfree\fR".
.TP
\fB\-\-version\fR
Versiyon bilgisini göster ve kapat.
.SH DETAYLAR İÇİN
.TP
\fBhttps://fedoraproject.org/wiki/Licensing:Main#Good_Licenses\fR
The Fedora Project wiki sayfası kabul görmüş yazılım lisanları içerir.
.TP
\fBhttps://vrms.alioth.debian.org/\fR
Orijinal programın ana sayfası \fBvrms\fR.
.SH LİSANS
Bu program GNU General Public lisansına göre ulaşılabilir ve Free Software
Foundation tarafından yayınlanmıştır
.SH YAZAR
2017'nin başında tarafından yazılmıştır\fBsuve\fR.
